import Head from "next/head";
import React from "react";
import { useStateValue } from "../globalStore/ContextProvider";

const Cart = () => {
  const [{ cart }] = useStateValue();
  console.log(cart);
  return (
    <div>
      <>
        <Head>
          <title>SneakyLegs</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="../images/icon.png" />
        </Head>
        <div>Cart</div>
      </>
    </div>
  );
};

export default Cart;
