import Head from "next/head";
import HeroSection from "../component/HeroSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>SneakyLegs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./public/images/icon.png" />
      </Head>
      <div>
        <HeroSection />
      </div>
    </div>
  );
}
