import Head from "next/head";
import About from "../component/About";
import Categories from "../component/Categories";
import Featured from "../component/Featured";
import Footer from "../component/Footer";
import Header from "../component/Header";
import HeroSection from "../component/HeroSection";

export default function Home() {
  return (
    <div>
      <Head>
        <title>SneakyLegs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./public/images/icon.png" />
      </Head>
      <div>
        <Header />
        <HeroSection />
        <About />
        <Categories />
        <Featured />
        <Footer />
      </div>
    </div>
  );
}
