import products from "../DB";
import Mencard from "../component/Mencard";
import styles from "../component/Product.module.css";
import Head from "next/head";
const Mensneakers = () => {
  return (
    <>
      <Head>
        <title>SneakyLegs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../images/icon.png" />
      </Head>
      <div className={styles.product__container}>
        {products
          .filter((product) => product.gender === "m")
          .map((filteredPerson) => (
            <Mencard key={filteredPerson.id} filteredPerson={filteredPerson} />
          ))}
      </div>
    </>
  );
};

export default Mensneakers;
