import ProductCard from "../component/ProductCard";
import styles from "../component/Product.module.css";
import Head from "next/head";
import { doc, getDoc } from "firebase/firestore";
import { db } from "../config/firebase";

export async function getServerSideProps() {
  const docRef = doc(db, "sneakylegs", "products");
  const docSnap = await getDoc(docRef);
  const data = docSnap.data();
  const dbData = data.products;
  return {
    props: { products: dbData },
  };
}

const Products = ({ products }) => {
  return (
    <>
      <Head>
        <title>SneakyLegs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../images/icon.png" />
      </Head>

      <div className={styles.product__container}>
        {products.map((a) => (
          <ProductCard product={a} key={a.id} />
        ))}
      </div>
    </>
  );
};

export default Products;
