import Head from "next/head";
import styles from "../component/Product.module.css";
import Women from "../component/Womencard";
import { doc, getDoc } from "firebase/firestore";
import { db } from "../config/firebase";

export async function getServerSideProps() {
  const docRef = doc(db, "sneakylegs", "products");
  const docSnap = await getDoc(docRef);
  const data = docSnap.data();
  const dbData = data.products;
  return {
    props: { products: dbData },
  };
}
const WomenSneakers = ({ products }) => {
  return (
    <>
      <Head>
        <title>SneakyLegs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../images/icon.png" />
      </Head>
      <div className={styles.product__container}>
        {products
          .filter((product) => product.gender === "f")
          .map((filteredPerson) => (
            <Women key={filteredPerson.id} filteredPerson={filteredPerson} />
          ))}
      </div>
    </>
  );
};

export default WomenSneakers;
